
//GRAMÁTICA DE INICIO
INICIO -> CONST VAR FUNCION INSTRUCCION

//GRAMÁTICA DE CONST
CONST -> const identificador = VALOR ";" | const identificador = VALOR ";" CONST |  λ

//GRAMÁTICA DE VAR
VAR -> var identificador = EXPRESION ";" | var identificador = EXPRESION ";" VAR |  λ

//GRAMÁTICA DE FUNCIÓN
FUNCION -> funcion identificador ( ARGUMENTO ) { INSTRUCCION } | funcion identificador ( ARGUMENTO ) { INSTRUCCION } FUNCION |  λ

//GRAMÁTICA DE INSTRUCCIÓN
INSTRUCCION -> LLAMAR_FUNCION | COMPARACION | CICLOS | ASIGNACION | λ

//GRAMÁTICA DE EXPRESIÓN
EXPRESION -> VALOR_BOOLEANO | EXPRESION_NUMERICA

//GRAMÁTICA DE VALOR
VALOR -> numero_entero | numero_real | VALOR_BOOLEANO

//GRAMÁTICA DE VALOR BOOLEANO
VALOR_BOOLEANO -> verdadero | falso

//GRAMÁTICA DE EXPRESION NUMÉRICA
EXPRESION_NUMERICA -> EXPRESION_CONJUNCION | EXPRESION_CONJUNCION "||" EXPRESION_CONJUNCION

//GRAMÁTICA DE EXPRESIÓN CONJUNCIÓN
EXPRESION_CONJUNCION -> EXPRESION_RELACIONAL | EXPRESION_RELACIONAL "&&" EXPRESION_RELACIONAL

//GRAMÁTICA DE EXPRESIÓN RELACIONAL
EXPRESION_RELACIONAL -> SIMBOLO_NEGACION EXPRESION_ARITMETICA | SIMBOLO_NEGACION EXPRESION_ARITMETICA SIMBOLO EXPRESION_ARITMETICA

//GRAMÁTICA DE SÍMBOLO
SIMBOLO -> ">" | "<" | ">=" | "<=" | "!=" | "==" | λ

//GRAMÁTICA DE SÍMBOLO NEGACIÓN
SIMBOLO_NEGACION -> "!" | λ

//GRAMÁTICA DE EXPRESIÓN ARITMETICA
EXPRESION_ARITMETICA -> TERMINO | TERMINO "+" TERMINO | TERMINO "-" TERMINO

//GRAMÁTICA DE TÉRMINO
TERMINO -> FACTOR | FACTOR "*" FACTOR | FACTOR "/"FACTOR | FACTOR "%" FACTOR

//GRAMÁTICA DE FACTOR
FACTOR -> "+" identificador | "-" identificador | identificdor | numero_entero | "+" numero_entero | "-" numero_entero | numero_real | "+" numero_real | "-" numero_real | FUNCIONES_CARRITO | "+" FUNCIONES_CARRITO | "-" FUNCIONES_CARRITO

//GRAMÁTICA DE LLAMAR FUNCIÓN
LLAMAR_FUNCION -> identificador ( PARAMETRO ) ";"|  FUNCIONES_CARRITO | identificador (  ) ";"

//GRAMÁTICA DE PÁRAMETROS
PARAMETRO -> identificador | identificador "," PARAMETRO 

//GRAMÁTICA DE COMPARACIÓN
COMPARACION  -> si ( EXPRESION ) { INSTRUCCION } |  si ( EXPRESION ) { INSTRUCCION } sino { INSTRUCCION } 

//GRAMÁTICA DE CICLOS
CICLOS -> mientras ( EXPRESION ) { INSTRUCCION }

//GRAMÁTICA DE ASIGNACIÓN
ASIGNACION -> identificador = EXPRESION ";"

//GRAMÁTICA FUNCIONES CARRITO
FUNCIONES_CARRITO -> comprobar_color | comprobar_pared_arriba | comprobar_pared_atras|comprobar_pared_derecha | comprobar_pared_izquierda | girar_izquierda | avanzar | apagate | parar |retroceder

//GRAMÁTICA ARGUMENTOS
ARGUMENTO -> TIPO_DATO identificador | TIPO_DATO identificador "," ARGUMENTO

//GRAMÁTICA TIPO DE DATO
TIPO_DATO -> booleano | numero_entero